jobs:
  build-test:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout DeepLinkDispatch
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Build/Test DeepLinkDispatch
      run: ./gradlew assemble check lintKotlin
name: Build/Test
on:
  repository_dispatch:
    types: trigger-ga___build_test.yml
