jobs:
  build-test:
    uses: airbnb/DeepLinkDispatch/.github/workflows/build_test.yml@master
  deploy-snapshot:
    needs: build-test
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout DeepLinkDispatch
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Update gradle.properties
      uses: DamianReeves/write-file-action@master
      with:
        contents: 'mavenCentralUsername=${{ secrets.NEXUS_USER }}

          mavenCentralPassword=${{ secrets.NEXUS_PASSWORD }}

          '
        path: gradle.properties
        write-mode: append
    - continue-on-error: true
      name: Deploy new snapshot of DeepLinkDispatch
      run: ./gradlew -PenforceSnapshotVersion=true publishAllPublicationsToMavenCentral
      shell: bash
name: Deploy snapshot
on:
  repository_dispatch:
    types: trigger-ga___deploy_snapshot.yml
